QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/ViewModels/Room/CreateRoomVM.cs
using QomfortHotelFinal.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;

namespace QomfortHotelFinal.Areas.Admin.ViewModels
{
    public class CreateRoomVM
    {
        [Required(ErrorMessage = "A RoomTitle must be included")]
        [MaxLength(100,ErrorMessage = "No more than 100 characters")]
        [MinLength(3,ErrorMessage = "No less than 3 characters")]
        public string Name { get; set; }
        [Required(ErrorMessage = "A Description must be included")]
        [MaxLength(256, ErrorMessage = "No more than 256 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Description { get; set; }
        [Required(ErrorMessage = "A Description must be included")]
        [MaxLength(256, ErrorMessage = "No more than 256 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string DetailDescription { get; set; }
        [Required(ErrorMessage = "A Price must be included")]
        [Range(1, 100000000, ErrorMessage = "There is no number less than 1 or more than 100000000")]

        public decimal Price { get; set; }
        [Required(ErrorMessage = "A size must be included")]
        [Range(1, 500, ErrorMessage = "There is no number less than 1 or more than 500")]

        public int Size { get; set; }
        [Required(ErrorMessage = "A Bed must be included")]
        [Range(1, 20, ErrorMessage = "There is no number less than 1 or more than 20")]

        public int Bed { get; set; }
        [Required(ErrorMessage = "A Capacity must be included")]
        [Range(1,50,ErrorMessage = "There is no number less than 1 or more than 50")]
        public int Capacity { get; set; }
        
        public bool Status { get; set; }

        public int CategoryId { get; set; }
        public List<Category>? Categorys { get; set; }
        public List<int> Serviceeids { get; set; }
        public List<int> Facilityids { get; set; }
        [Range(1, 20, ErrorMessage = "There is no number less than 1 or more than 20")]
        [Required(ErrorMessage = "A Bathroom must be included")]

        public int BathRoom { get; set; }
       
        public List<Facility>? Facilitiys { get; set;}
      
        public List<Servicee>? Servicees { get; set; }
        [Required(ErrorMessage = "A FacilityName must be included")]
        [NotMapped]
        public IFormFile? MainPhoto { get; set; }
        [Required(ErrorMessage = "A FacilityName must be included")]
        [NotMapped]

        public List<IFormFile>? Photos { get; set; }
            
       
    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/ViewModels/Room/UpdateRoomVM.cs
using QomfortHotelFinal.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QomfortHotelFinal.Areas.Admin.ViewModels
{
    public class UpdateRoomVM
    {
        [MaxLength(100, ErrorMessage = "No more than 100 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Name { get; set; }
        [MaxLength(256, ErrorMessage = "No more than 256 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Description { get; set; }
        [MaxLength(256, ErrorMessage = "No more than 256 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string DetailDescription { get; set; }
        [Range(1, 100000000, ErrorMessage = "There is no number less than 1 or more than 100000000")]
        public decimal Price { get; set; }
        [Range(1, 500, ErrorMessage = "There is no number less than 1 or more than 500")]
        public int Size { get; set; }
        [Range(1, 20, ErrorMessage = "There is no number less than 1 or more than 20")]
        public int Bed { get; set; }
        [Range(1, 50, ErrorMessage = "There is no number less than 1 or more than 50")]
        public int Capacity { get; set; }
        public int CategoryId { get; set; }
        public List<Category>? Categorys { get; set; }
        public List<int> Serviceeids { get; set; }
        public List<int> Facilityids { get; set; }
        [Range(1, 20, ErrorMessage = "There is no number less than 1 or more than 20")]
        public int BathRoom { get; set; }
        public List<Facility>? Facilitiys { get; set; }
        public List<Servicee>? Servicees { get; set; }
        [NotMapped]
        public IFormFile MainPhoto { get; set; }
        [NotMapped] 
        public List<IFormFile>? Photos { get; set; }
        public List<int> Imageids { get; set; }
        public List<RoomImage>? RoomImages { get; set; }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Models/Room.cs
namespace QomfortHotelFinal.Models
{
    public class Room
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DetailDescription { get; set; }
        public decimal Price { get; set; }
        public int Size { get; set; }
        public int Bed { get; set; }
        public int Capacity { get; set; }
        public int CategoryId { get; set; }
        public List<RoomImage>? RoomImages { get; set; }
        public int BathRoom { get; set; }
        public Category Category { get; set; }
        public List<RoomFacility>? RoomFacilities { get; set; }
        public List<RoomService>? RoomServicees { get; set; }
        public bool? Status { get; set; }
        public List<Reservation>? Reservations { get; set; }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Controllers/RoomController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using QomfortHotelFinal.Areas.Admin.ViewModels;
using QomfortHotelFinal.DAL;
using QomfortHotelFinal.Models;
using QomfortHotelFinal.Utilities.Exceptions;
using QomfortHotelFinal.Utilities.Extensions;

namespace QomfortHotelFinal.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
   
    public class RoomController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public RoomController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

       
        [Authorize(Roles = "Admin,Memmber")]
        public async Task<IActionResult> Index(int page = 1)
        {
            if (page < 1) throw new WrongRequestException("The query is incorrect");

            int count = await _context.Rooms.CountAsync();

            List<Room> Rooms = await _context.Rooms.Skip((page - 1) * 3).Take(3)
                .Include(p => p.Category)
                .Include(x=>x.Reservations)
                .Include(p => p.RoomImages.Where(pi => pi.IsPrimary == true))
                .Include(p => p.RoomServicees)
                .ThenInclude(pt => pt.Servicee)
                 .Include(p => p.RoomFacilities)
                .ThenInclude(pt => pt.Facility)
                .ToListAsync();
            if(Rooms==null) throw new NotFoundException("Room not found");

            PaginateVM<Room> pagvm = new PaginateVM<Room>
            {
                Items = Rooms,
                TotalPage = Math.Ceiling((double)count / 3),
                CurrentPage = page,
            };

            return View(pagvm);
        }
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Create()
        {
            CreateRoomVM vm = new CreateRoomVM();

            vm.Categorys = await _context.Categories.ToListAsync();
            vm.Facilitiys = await _context.Facilities.ToListAsync();
            vm.Servicees = await _context.Servisees.ToListAsync();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRoomVM vm)
        {
            vm.Categorys = await _context.Categories.ToListAsync();
            vm.Facilitiys = await _context.Facilities.ToListAsync();
            vm.Servicees = await _context.Servisees.ToListAsync();
            if (!ModelState.IsValid)
            {
               
                return View(vm);
            }
            bool result = await _context.Categories.AnyAsync(c => c.Id == vm.CategoryId);

            if (!result)
            {
              
                ModelState.AddModelError("CategoryId", "Bu id li category movcud deyil");
                return View(vm);
            }
            foreach (int item in vm.Serviceeids)
            {
                bool Serviceeresult = await _context.Servisees.AnyAsync(t => t.Id == item);
                if (!Serviceeresult)
                {
                   
                    ModelState.AddModelError("ServiceeIds", "Bu id li Servicee movcud deyil");
                    return View(vm);
                }
            }
            foreach (int item in vm.Facilityids)
            {
                bool cresult = await _context.Facilities.AnyAsync(t => t.Id == item);
                if (!cresult)
                {
                    
                    ModelState.AddModelError("Facilityids", "Bu id li Facility movcud deyil");
                    return View(vm);
                }
            }
            if (vm.Price <= 10)
            {
                ModelState.AddModelError("Price", "No quantity less than 10");
                return View(vm);
            }
            if (vm.Bed <= 0)
            {
                ModelState.AddModelError("Bed", "No quantity less than 0");
                return View(vm);
            }

            if (vm.BathRoom <= 0)
            {
                ModelState.AddModelError("BathRoom", "No quantity less than 0");
                return View(vm);
            }

            if (vm.MainPhoto is not null)
            {
                if (!vm.MainPhoto.ValidateType("image/"))
                {

                    ModelState.AddModelError("MainPhoto", "Fayl tipi uyqun deyil");
                    return View(vm);
                }

                if (!vm.MainPhoto.ValidateSize(600))
                {


                    ModelState.AddModelError("MainPhoto", "Fayl olcusu uyqun deyil");
                    return View(vm);

                }

            }
                       

            RoomImage main = new RoomImage
            {
                IsPrimary = true,
                Url = await vm.MainPhoto.CreateFileAsync(_env.WebRootPath, "assets", "images", "rooms")

            };
           
            Room Room = new Room
            {
                Status = true,
                Name=vm.Name.Capitalize(),
                Description=vm.Description, 
                DetailDescription=vm.DetailDescription,
                Price=vm.Price,
                Size=vm.Size,
                Bed=vm.Bed,
                Capacity=vm.Capacity,
                BathRoom=vm.BathRoom,   
                CategoryId = (int)vm.CategoryId,
                RoomServicees = new List<RoomService>(),
                RoomFacilities = new List<RoomFacility>(),
                RoomImages = new List<RoomImage> { main}



            };
           

            TempData["Message"] = "";

            foreach (IFormFile photo in vm.Photos ?? new List<IFormFile>())
            {
                if (!photo.ValidateType("image/"))
                {
                    TempData["Message"] += $" <p class=\"text-danger\">{photo.FileName}  file tipi uyqun deyil</p>";
                    continue;
                }
                if (!photo.ValidateSize(600))
                {
                    TempData["Message"] += $"<p class=\"text-danger\">{photo.FileName}  file olcusu uyqun deyil</p>";

                    continue;
                }

                Room.RoomImages.Add(new RoomImage
                {
                    IsPrimary = null,
                    Url = await photo.CreateFileAsync(_env.WebRootPath, "assets", "images", "rooms")

                });

            }

            foreach (var item in vm.Serviceeids)
            {
                RoomService pServicee = new RoomService
                {
                    ServiceeId = item,
                };
                Room.RoomServicees.Add(pServicee);
            }
            foreach (var item in vm.Facilityids)
            {
                RoomFacility cServicee = new RoomFacility
                {
                    FacilityId = item,
                };
                Room.RoomFacilities.Add(cServicee);
            }
          
            await _context.Rooms.AddAsync(Room);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");
            Room Room = await _context.Rooms
                .Include(p => p.RoomServicees)
                .Include(p => p.RoomImages)
                .Include(p => p.RoomFacilities)
                .FirstOrDefaultAsync(p => p.Id == id);
            if (Room == null) throw new NotFoundException("Room not found");

            UpdateRoomVM vm = new UpdateRoomVM
            {
                Name = Room.Name,
                Price = Room.Price,
                Bed = Room.Bed,
                Size = Room.Size,
                Capacity = Room.Capacity,
                BathRoom = Room.BathRoom,
                Description = Room.Description,
                DetailDescription = Room.DetailDescription,
                CategoryId = Room.CategoryId,
                RoomImages = Room.RoomImages,
                Serviceeids = Room.RoomServicees.Select(p => p.ServiceeId).ToList(),
                Facilityids = Room.RoomFacilities.Select(p => p.FacilityId).ToList(),
                Categorys = await _context.Categories.ToListAsync(),
                Servicees = await _context.Servisees.ToListAsync(),
                Facilitiys = await _context.Facilities.ToListAsync(),

            };


            await _context.SaveChangesAsync();


            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateRoomVM pvm)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");
            Room exsist = await _context.Rooms
              .Include(p => p.RoomServicees)
              .Include(p => p.RoomFacilities)
              .Include(p => p.RoomImages)
              .FirstOrDefaultAsync(p => p.Id == id);
            if (exsist == null) throw new NotFoundException("Room not found");

            pvm.Categorys = await _context.Categories.ToListAsync();
            pvm.Servicees = await _context.Servisees.ToListAsync();
            pvm.Facilitiys = await _context.Facilities.ToListAsync();
            pvm.RoomImages = exsist.RoomImages;
            if (!ModelState.IsValid)
            {
               
                return View(pvm);
            }
            if (pvm.Price <= 10)
            {
                ModelState.AddModelError("Price", "No quantity less than 10");
                return View(pvm);
            }
            if (pvm.Capacity <= 0)
            {
                ModelState.AddModelError("Capacity", "No quantity less than 0");
                return View(pvm);
            }
            if (pvm.Bed <= 0)
            {
                ModelState.AddModelError("Bed", "No quantity less than 0");

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Room/Create.cshtml
@model CreateRoomVM

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create Room</h4>

                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label asp-for="MainPhoto">Main Image</label>
                                <input asp-for="MainPhoto" class="form-control" accept="image/*">
                                <span class="text-danger" asp-validation-for="MainPhoto"></span>
                            </div>
                            
                            <div class="form-group">
                                <label asp-for="Photos">Additional Images</label>
                                <input asp-for="Photos" class="form-control" accept="image/*">
                                <span class="text-danger" asp-validation-for="Photos"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price">Price</label>
                                <input asp-for="Price" class="form-control" placeholder="Price">
                                <span class="text-danger" asp-validation-for="Price"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Capacity">Capacity</label>
                                <input asp-for="Capacity" class="form-control" placeholder="Capacity">
                                <span class="text-danger" asp-validation-for="Capacity"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Description</label>
                                <input asp-for="Description" class="form-control" placeholder="Description">
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DetailDescription">DetailDescription</label>
                                <input asp-for="DetailDescription" class="form-control" placeholder="DetailDescription">
                                <span class="text-danger" asp-validation-for="DetailDescription"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Bed">Bed</label>
                                <input asp-for="Bed" class="form-control" placeholder="Bed">
                                <span class="text-danger" asp-validation-for="Bed"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Size">Size</label>
                                <input asp-for="Size" class="form-control" placeholder="Size">
                                <span class="text-danger" asp-validation-for="Size"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BathRoom">BathRoom</label>
                                <input asp-for="BathRoom" class="form-control" placeholder="BathRoom">
                                <span class="text-danger" asp-validation-for="BathRoom"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoryId">Category</label>

                                <select asp-for="CategoryId" class="form-control" asp-items="new SelectList(Model.Categorys,nameof(Category.Id),nameof(Category.Name))">
                                    <option disabled selected> Chosse Category </option>
                                </select>

                                <span class="text-danger" asp-validation-for="CategoryId"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Facilityids">Facility</label>

                                <select asp-for="Facilityids" class="form-control" asp-items="new SelectList(Model.Facilitiys,nameof(Facility.Id),nameof(Facility.Name))">
                                </select>

                                <span class="text-danger" asp-validation-for="Facilityids"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Serviceeids">Servicee</label>

                                <select asp-for="Serviceeids" class="form-control" asp-items="new SelectList(Model.Servicees,nameof(Servicee.Id),nameof(Servicee.Name))">
                                </select>

                                <span class="text-danger" asp-validation-for="Serviceeids"></span>
                            </div>
                           
                           

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Room/Index.cshtml
@model PaginateVM<Room>
@{
    int count = (Model.CurrentPage - 1) * 3;
}

<br />
<br />
<br />
<br />
<br />
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Room Table</h4>
                        @{
                            if (!User.IsInRole("Memmber"))
                            {
                                <a asp-action="Create" asp-controller="Room" class="btn btn-outline-info">Ceate Room</a>
                            }
                        }
                    
                        <div class="table-responsive">
                            <table class="table table-dark table-borderless mb-0">
                                <thead>
                                    <tr>
                                        <th>
                                            No
                                        </th>
                                        <th>
                                            Image
                                        </th>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Price
                                        </th>
                                        <th>
                                            Bed
                                        </th>
                                        <th>
                                            Capacity
                                        </th>
                                        <th>
                                            Category
                                        </th>
                                      
                                       
                                        <th>

                                            Settings
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (Room item in Model.Items)
                                    {
                                        count++;
                                        <tr>
                                            <td>
                                                @count
                                            </td>

                                            <td>
                                                <img style="width:150px;height:150px;" src="~/assets/images/rooms/@item.RoomImages.FirstOrDefault(x=>x.IsPrimary==true)?.Url" />
                                            </td>
                                            <td>
                                                @item.Name
                                            </td>
                                            <td>
                                               $@item.Price
                                            </td><td>
                                                @item.Bed
                                            </td>
                                            <td>
                                                @item.Capacity
                                            </td>
                                            <td>
                                                @item.Category.Name
                                            </td>
                                           
                                            <td>
                                                @{
                                                    if (!User.IsInRole("Memmber"))
                                                    {
                                                        <a asp-action="Update" asp-controller="Room" asp-route-id="@item.Id" class="btn btn-warning btn-info"><i class="mdi mdi-grease-pencil"></i></a>
                                                        <a asp-action="Delete" asp-controller="Room" asp-route-id="@item.Id" class="customDeletebtn btn btn-danger btn-info" class=""><i class="mdi mdi-delete"></i></a>
                                                    }
                                                }
                                               
                                                <a asp-action="Reserv" asp-controller="Room" asp-route-id="@item.Id" asp-route-area="" class="btn btn-outline-info"><i class="mdi mdi-open-in-new"></i></a>
                                            </td>
                                        </tr>

                                    }

                                </tbody>
                            </table>
                        </div>
                        <nav aria-label="Page navigation example">
                            <ul class="pagination" class="sub-menu" aria-expanded="false">
                                <li class="page-item @(Model.CurrentPage<=1?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-1)" asp-action="index" asp-controller="Room">Previous</a></li>
                                @for (int i = 0; i < Model.TotalPage; i++)
                                {
                                    <li class="page-item @(Model.CurrentPage - 1 == i? "active":"")"><a class="page-link" asp-route-page="@(i+1)" asp-action="index" asp-controller="Room">@(i + 1)</a></li>
                                }

                                <li class="page-item @(Model.TotalPage<=Model.CurrentPage?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage+1)" asp-action="index" asp-controller="Room">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- end card-body-->
                </div>
                <!-- end card -->

            </div>
        </div>
    </div>
</div>