QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/ViewModels/Gallery/CreateGalleryVM.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QomfortHotelFinal.Areas.Admin.ViewModels.Gallery
{
    public class CreateGalleryVM
    {

        [Required(ErrorMessage = "A ImageName must be included")]
        [MaxLength(100, ErrorMessage = "No more than 100 characters")]
        [MinLength(4, ErrorMessage = "Be less than 4 characters")]

        public string Name { get; set; }
        [Required(ErrorMessage = "A Photo must be included")]
        [NotMapped]
        public IFormFile? Photo { get; set; }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/ViewModels/Gallery/UpdateGalleryVM.cs
using System.ComponentModel.DataAnnotations;

namespace QomfortHotelFinal.Areas.Admin.ViewModels.Gallery
{
    public class UpdateGalleryVM
    {
        [MaxLength(100, ErrorMessage = "No more than 100 characters")]
        [MinLength(4, ErrorMessage = "Be less than 4 characters")]
        public string Name { get; set; }
        public string Image { get; set; }
        public IFormFile? Photo { get; set; }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Models/Gallery.cs
namespace QomfortHotelFinal.Models
{
    public class Gallery
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QomfortHotelFinal.Areas.Admin.ViewModels;
using QomfortHotelFinal.Areas.Admin.ViewModels.Gallery;
using QomfortHotelFinal.DAL;
using QomfortHotelFinal.Models;
using QomfortHotelFinal.Utilities.Exceptions;
using QomfortHotelFinal.Utilities.Extensions;

namespace QomfortHotelFinal.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    public class GalleryController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public GalleryController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        [Authorize(Roles = "Admin,Memmber")]

        public async Task<IActionResult> Index(int page = 1)
        {
            int count = await _context.Galleries.CountAsync();

            List<Gallery> Gallerys = await _context.Galleries.Skip((page - 1) * 3).Take(3).ToListAsync();

            PaginateVM<Gallery> pagvm = new PaginateVM<Gallery>
            {
                Items = Gallerys,
                TotalPage = Math.Ceiling((double)count / 3),
                CurrentPage = page,
            };

            return View(pagvm);
        }

        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateGalleryVM Galleryvm)
        {
                        
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (Galleryvm.Photo is not null)
            {
                if (!Galleryvm.Photo.ValidateType("image/"))
                {
                    ModelState.AddModelError("Photo", "File tipi uyqun deyil");
                    return View();
                }

                if (!Galleryvm.Photo.ValidateSize(2 * 1024))
                {
                    ModelState.AddModelError("Photo", "File olcusu 2-mb den boyuk olmamalidir");
                    return View();

                }

            }
            string filename = await Galleryvm.Photo.CreateFileAsync(_env.WebRootPath, "assets", "images", "gallery");


            Gallery Gallery = new Gallery
            {
                Image = filename,
                Name = Galleryvm.Name.Capitalize(),
               

            };
            await _context.Galleries.AddAsync(Gallery);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");
            Gallery exsist = await _context.Galleries.FirstOrDefaultAsync(s => s.Id == id);
            if (exsist == null) throw new NotFoundException("Gallery not found");

            UpdateGalleryVM Galleryvm = new UpdateGalleryVM
            {
              
                Image = exsist.Image,
                Name = exsist.Name
            };

            return View(Galleryvm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateGalleryVM Galleryvm)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");

            if (!ModelState.IsValid)
            {
                return View(Galleryvm);
            }

            Gallery exsist = await _context.Galleries.FirstOrDefaultAsync(s => s.Id == id);
            if (exsist == null) return NotFound();

            if (Galleryvm.Photo is not null)
            {
                if (!Galleryvm.Photo.ValidateType("image/"))
                {
                    ModelState.AddModelError("Photo", "File tipi uyqun deyil");
                    return View(Galleryvm);
                }

                if (!Galleryvm.Photo.ValidateSize(2 * 1024))
                {
                    ModelState.AddModelError("Photo", "File olcusu 2-mb den boyuk olmamalidir");
                    return View(Galleryvm);

                }
                string filename = await Galleryvm.Photo.CreateFileAsync(_env.WebRootPath, "assets", "images", "gallery");
                exsist.Image.DeleteFile(_env.WebRootPath, "assets", "images", "gallery");
                exsist.Image = filename;
            }
            exsist.Name = Galleryvm.Name.Capitalize();
          
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Admin")]


        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");
            Gallery exsist = await _context.Galleries.FirstOrDefaultAsync(s => s.Id == id);
            if (exsist == null) return Json(new { status = 404 });
            try
            {


                exsist.Image.DeleteFile(_env.WebRootPath, "assets", "image", "gallery");
                _context.Galleries.Remove(exsist);
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {

                return Json(new { status = 500 });
            }

            return Json(new { status = 200 });

        }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Gallery/Create.cshtml
@using QomfortHotelFinal.Areas.Admin.ViewModels.Gallery;
@model CreateGalleryVM
<br />
<br />
<br />
<br />
<br />
<br />
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create Gallery</h4>

                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" class="form-control" placeholder="Photo" accept="image/*">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button asp-action="Index" class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Gallery/Index.cshtml
@model PaginateVM<Gallery>
@{
    int count = (Model.CurrentPage - 1) * 3;
}

<br />
<br />
<br />
<br />
<br />
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Gallery Table</h4>
                        @{
                            if (!User.IsInRole("Memmber"))
                            {
                                <a asp-action="Create" asp-controller="Gallery" class="btn btn-outline-info">Ceate Gallery</a>
                            }
                        }
                      
                        <div class="table-responsive">
                            <table class="table table-dark table-borderless mb-0">
                                <thead>
                                    <tr>
                                        <th>
                                            No
                                        </th>
                                        <th>
                                            Image
                                        </th>
                                        <th>
                                            Name
                                        </th>
                                        @{
                                            if (!User.IsInRole("Memmber"))
                                            {
                                                <th>

                                                    Settings
                                                </th>
                                            }
                                        }

                                       

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (Gallery item in Model.Items)
                                    {
                                        count++;
                                        <tr>
                                            <td>
                                                @count
                                            </td>

                                            <td>
                                                <img style="width:100px;height:100px;" src="~/assets/images/gallery/@item.Image" />
                                            </td>
                                            <td>
                                                @item.Name
                                            </td>
                                           
                                            <td>
                                                @{
                                                    if (!User.IsInRole("Memmber"))
                                                    {
                                                        <a asp-action="Update" asp-controller="Gallery" asp-route-id="@item.Id" class="btn btn-warning btn-info"><i class="mdi mdi-grease-pencil"></i></a>
                                                        <a asp-action="Delete" asp-controller="Gallery" asp-route-id="@item.Id" class="customDeletebtn btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
                                                    }
                                                }

                                            </td>
                                        </tr>

                                    }

                                </tbody>
                            </table>
                        </div>
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                <li class="page-item @(Model.CurrentPage<=1?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-1)" asp-action="index" asp-controller="Gallery">Previous</a></li>
                                @for (int i = 0; i < Model.TotalPage; i++)
                                {
                                    <li class="page-item @(Model.CurrentPage - 1 == i? "active":"")"><a class="page-link" asp-route-page="@(i+1)" asp-action="index" asp-controller="Gallery">@(i + 1)</a></li>
                                }

                                <li class="page-item @(Model.TotalPage<=Model.CurrentPage?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage+1)" asp-action="index" asp-controller="Gallery">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- end card-body-->
                </div>
                <!-- end card -->

            </div>
        </div>
    </div>
</div>

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Gallery/Update.cshtml
@using QomfortHotelFinal.Areas.Admin.ViewModels.Gallery;
@model UpdateGalleryVM
<br />
<br />
<br />
<br />
<br />
<br />
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Update Gallery</h4>

                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <img style="width:200px;height:200px;" src="~/assets/images/gallery/@Model.Image" />
                                <input asp-for="Image" type="hidden" class="form-control">

                            </div>
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" class="form-control" placeholder="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>

                           
                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button asp-action="Index" class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>