QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/ViewModels/Servicee/CreateServiceVM.cs
using System.ComponentModel.DataAnnotations;

namespace QomfortHotelFinal.Areas.Admin.ViewModels
{
    public class CreateServiceVM
    {
        [Required(ErrorMessage = "A Name must be included")]
        [MaxLength(100, ErrorMessage = "No more than 100 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Name { get; set; }
        [Required(ErrorMessage = "A Description must be included")]
        [MaxLength(256, ErrorMessage = "No more than 256 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Description { get; set; }
        [Required(ErrorMessage = "A RoomTitle must be included")]
        [MaxLength(60, ErrorMessage = "No more than 60 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Icon { get; set; }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/ViewModels/Servicee/UpdateServiceVM.cs
using System.ComponentModel.DataAnnotations;

namespace QomfortHotelFinal.Areas.Admin.ViewModels
{
    public class UpdateServiceVM
    {
        [MaxLength(100, ErrorMessage = "No more than 100 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Name { get; set; }
        [MaxLength(256, ErrorMessage = "No more than 256 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Description { get; set; }
        [MaxLength(60, ErrorMessage = "No more than 60 characters")]
        [MinLength(3, ErrorMessage = "No less than 3 characters")]
        public string Icon { get; set; }
    }
}

QomfortHotelFinal/QomfortHotelFinal/Models/Servicee.cs
namespace QomfortHotelFinal.Models
{
    public class Servicee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public List<RoomFacility>? RoomServicees { get; set; }

    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Controllers/ServiceeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QomfortHotelFinal.Areas.Admin.ViewModels;
using QomfortHotelFinal.DAL;
using QomfortHotelFinal.Models;
using QomfortHotelFinal.Utilities.Exceptions;
using QomfortHotelFinal.Utilities.Extensions;

namespace QomfortHotelFinal.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    public class ServiceeController : Controller
    {
        private readonly AppDbContext _context;

        public ServiceeController(AppDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Admin,Memmber")]

        public async Task<IActionResult> Index(int page = 1)
        {
            if (page < 1) throw new WrongRequestException("The query is incorrect");

            int count = await _context.Servisees.CountAsync();
            List<Servicee> service = await _context.Servisees.Include(p=>p.RoomServicees).Skip((page - 1) * 3).Take(3).ToListAsync();
            PaginateVM<Servicee> pagvm = new PaginateVM<Servicee>
            {
                Items = service,
                TotalPage = Math.Ceiling((double)count / 3),
                CurrentPage = page,
            };

            return View(pagvm);
        }
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateServiceVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View();

            }
            bool result = _context.Servisees.Any(c => c.Name.Trim() == vm.Name.Trim());
            if (result)
            {
                ModelState.AddModelError("Name", "Bu adda Servicee movcuddur");
                return View();
            }

            Servicee Servicee = new Servicee
            {
                Name = vm.Name.Capitalize(),
                Icon = vm.Icon,
                Description = vm.Description
            };
            await _context.Servisees.AddAsync(Servicee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]

        //UPDATE 
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");
            Servicee Servicee = await _context.Servisees.FirstOrDefaultAsync(c => c.Id == id);
            if (Servicee == null) throw new NotFoundException("Services not found");
            UpdateServiceVM vm = new UpdateServiceVM
            {
                Name = Servicee.Name.Capitalize(),
                Icon = Servicee.Icon,
                Description = Servicee.Description  
                
            };

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateServiceVM Serviceevm)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");
            if (!ModelState.IsValid)
            {
                return View();
            }
            Servicee exsisted = await _context.Servisees.FirstOrDefaultAsync(c => c.Id == id);
            if (exsisted == null) throw new NotFoundException("Services not found");
            bool result = await _context.Servisees.AnyAsync(c => c.Name == Serviceevm.Name.Capitalize() && c.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "Bu adda Servicee atriq movcuddur");

                return View();
            }
            exsisted.Name = Serviceevm.Name.Capitalize();
            exsisted.Icon = Serviceevm.Icon;    
            exsisted.Description = Serviceevm.Description;  
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]


        //DELETE

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) throw new WrongRequestException("The query is incorrect");

            Servicee existed = await _context.Servisees.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) return Json(new { status = 404 });
            try
            {

                _context.Servisees.Remove(existed);
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {

                return Json(new { status = 500 });
            }

            return Json(new { status = 200 });
           
           
           
        }


    }
}

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Servicee/Create.cshtml
@model CreateServiceVM
<br />
<br />
<br />
<br />
<br />
<br />
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create Category</h4>

                        <form class="forms-sample" method="post">
                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Description</label>
                                <input asp-for="Description" class="form-control" placeholder="Description">
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Icon">Icon</label>
                                <input asp-for="Icon" class="form-control" placeholder="Icon">
                                <span class="text-danger" asp-validation-for="Icon"></span>
                            </div>
                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button asp-action="Index" class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Servicee/Index.cshtml
@model PaginateVM<Servicee>
@{
    int count = (Model.CurrentPage - 1) * 3;
}

<br />
<br />
<br />
<br />
<br />
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Servicee Table</h4>
                        @{
                            if (!User.IsInRole("Memmber"))
                            {
                                <a asp-action="Create" asp-controller="Servicee" class="btn btn-outline-info">Ceate Servicee</a>
                            }
                        }
                     
                        <div class="table-responsive">
                            <table class="table table-dark table-borderless mb-0">
                                <thead>
                                    <tr>
                                        <th>
                                            No
                                        </th>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Room Count
                                        </th>
                                        <th>
                                           Description
                                        </th>
                                        
                                        @{
                                            if (!User.IsInRole("Memmber,Blogger"))
                                            {
                                                <th>

                                                    Settings
                                                </th>
                                            }
                                        }


                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (Servicee item in Model.Items)
                                    {
                                        count++;
                                        <tr>
                                            <td>
                                                @count
                                            </td>

                                            <td>
                                                @item.Name
                                            </td>
                                            <td>
                                                @item.RoomServicees.Count
                                            </td>
                                            <td>
                                                @item.Description
                                            </td>
                                            <td>
                                                @{
                                                    if (!User.IsInRole("Memmber"))
                                                    {
                                                        <a asp-action="Update" asp-controller="Servicee" asp-route-id="@item.Id" class="btn btn-warning btn-info"><i class="mdi mdi-grease-pencil"></i></a>
                                                        <a asp-action="Delete" asp-controller="Servicee" asp-route-id="@item.Id" class="customDeletebtn btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
                                                    }
                                                }
                                               
                                            </td>
                                        </tr>

                                    }

                                </tbody>
                            </table>
                        </div>
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                <li class="page-item @(Model.CurrentPage<=1?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-1)" asp-action="index" asp-controller="Servicee">Previous</a></li>
                                @for (int i = 0; i < Model.TotalPage; i++)
                                {
                                    <li class="page-item @(Model.CurrentPage - 1 == i? "active":"")"><a class="page-link" asp-route-page="@(i+1)" asp-action="index" asp-controller="Servicee">@(i + 1)</a></li>
                                }

                                <li class="page-item @(Model.TotalPage<=Model.CurrentPage?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage+1)" asp-action="index" asp-controller="Servicee">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- end card-body-->
                </div>
                <!-- end card -->

            </div>
        </div>
    </div>
</div>

QomfortHotelFinal/QomfortHotelFinal/Areas/Admin/Views/Servicee/Update.cshtml
@model UpdateServiceVM
<br />
<br />
<br />
<br />
<br />
<br />
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Update Category</h4>

                        <form class="forms-sample" method="post">
                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Description</label>
                                <input asp-for="Description" class="form-control" placeholder="Description">
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Icon">Icon</label>
                                <input asp-for="Icon" class="form-control" placeholder="Icon">
                                <span class="text-danger" asp-validation-for="Icon"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button asp-action="Index" class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>